[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]

[dependencies]
forge-std = "1.9.7"
"@openzeppelin-contracts" = "5.4.0"
smartcontractkit-chainlink = "2.26.0"
"@chainlink-contracts" = "1.4.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
