[profile.default]
src = "src"
out = "out"
libs = ["lib"]


remappings = [
  "@solady-utils/=lib/solady/src/utils" 
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
